name: CD

on:
  push:
    tags: "v*.*.*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            aarch64-unknown-linux-gnu,
            # i686-unknown-linux-gnu,
            # x86_64-unknown-linux-gnu,
            # x86_64-unknown-linux-musl,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --manifest-path=./statico/Cargo.toml --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd statico/target/${{ matrix.target }}/release          
          tar czvf ../../../statico-${{ matrix.target }}.tar.gz statico
          cd ../../../
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "statico-*.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
