name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          make clean
          make

  release:
    name: release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          [
            aarch64-unknown-linux-gnu,
            i686-unknown-linux-gnu,
            x86_64-unknown-linux-gnu,
            x86_64-unknown-linux-musl,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --manifest-path=./statico/Cargo.toml --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd statico/target/${{ matrix.target }}/release          
          tar czvf ../../../statico-${{ matrix.target }}.tar.gz compiledbin
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "compiledbin*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
